## Part A - Basics of Tensors

In [2]:
import torch
import numpy as np

[Numpy](https://numpy.org/doc/stable/user/whatisnumpy.html) is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. [[1](https://cs231n.github.io/python-numpy-tutorial/#numpy)]

Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing. [[2](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html)]

PyTorch interoperates well with NumPy. Below we create a NumPy array, convert it into a PyTorch Tensor, then back into a NumPy array. This is important because most datasets you’ll work with will likely be read and preprocessed as Numpy arrays. [[3](https://medium.com/swlh/pytorch-basics-tensors-and-gradients-eb2f6e8a6eee)]

In [3]:
x = np.array([[1, 1], [3, 3.]])
x

array([[1., 1.],
       [3., 3.]])

In [4]:
y = torch.from_numpy(x)
y

tensor([[1., 1.],
        [3., 3.]], dtype=torch.float64)

In [7]:
z = y.numpy()
z

array([[1., 1.],
       [3., 3.]])

In [8]:
# verifying that x, y and z have the same data types
x.dtype, y.dtype, z.dtype

(dtype('float64'), torch.float64, dtype('float64'))

A tensor can be a number, vector, matrix as well as any n-dimensional array.

In [9]:
a = torch.tensor(1.)
a

tensor(1.)

In [10]:
b = torch.tensor([1., 2, 3, 4])
b

tensor([1., 2., 3., 4.])

In [11]:
c = torch.tensor([[1., 1], [2, 2], [3, 3]])
c

tensor([[1., 1.],
        [2., 2.],
        [3., 3.]])

In [12]:
# 3D array
d = torch.tensor([
    [[1, 2, 3], 
     [3, 4, 5]], 
    [[5, 6, 7], 
     [7, 8, 9.]]])
d

tensor([[[1., 2., 3.],
         [3., 4., 5.]],

        [[5., 6., 7.],
         [7., 8., 9.]]])

In [16]:
a.shape, b.shape, c.shape, d.shape

(torch.Size([]), torch.Size([4]), torch.Size([3, 2]), torch.Size([2, 2, 3]))

More PyTorch Tensor functions are explored in my blog post [here](https://medium.com/swlh/exploring-5-pytorch-tensor-functions-for-beginners-f740fd04c258).

## Part B - Gradients

One other special thing about PyTorch, is that every Tensor has a `requires_grad` (default is set to False) flag, so that when we call the `.backward` method, we are able to compute derivatives automatically.

We will come to understand why Gradients are important shortly.

Below you will find an example of how we calculate these gradients and basic tensor arithmetic operations.

In [17]:
x = torch.tensor(10.)
w = torch.tensor(15., requires_grad=True)
b = torch.tensor(20., requires_grad=True)

In [18]:
y = w * x + b
y

tensor(170., grad_fn=<AddBackward0>)

In [19]:
y.backward() # As mentioned above, this method computes the derivatives.

In [20]:
# We can see the derivatives of y with respect to their input tensors, through using the .grad flag.
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(10.)
dy/db: tensor(1.)


More about PyTorch gradients can be found in [this great video series](https://www.youtube.com/watch?v=DbeIqrwb_dE&list=PLqnslRFeH2UrcDBWF5mfPGpqQDSta6VK4&index=3&ab_channel=PythonEngineer).